### ISSUE TITLE
serverless schema does not support ${} everywhere

### ISSUE THREAD

**Issue by gildas** [lalcebo/json-schema#133]
In many places, when we use $(), vscode complains about errors since reference.json does not have support for this.

Example:
```
resources:
  Resources:
    Bucket:
      Properties:
        BucketName: ${self:custom.bucketName}
```
