### ISSUE TITLE
serverless schema layers shouldn't have path as a required param

### ISSUE THREAD

**Issue by vighnesh153** [lalcebo/json-schema#141]
In serverless.yml version 3, we can provide an artifact zip directly instead of providing a path to the layer directory. 

Sample:
```yml
layers:
  MyLayer:
    package:
      artifact: layer/output.zip
```

I think [this block][1] should be removed.

  [1]: https://github.com/lalcebo/json-schema/blob/dff2dceadc8157ef2a926cf4ecfc254129c42e3d/serverless/components/layers.json#L73-L75
