### ISSUE TITLE
Serverless schema SQS event in lambda doesn't support `Fn::GetAtt`

### ISSUE THREAD

**Issue by akbarcandrawarsa** [lalcebo/json-schema#142]
I have the following serverless.yml and vscode complaints error `IncorrectType`. I think it is common to use `Fn::GetAtt` to retrieve a SQS queue Arn.
Example:
```yml
functions:
  MyLambda:
    events:
      - sqs:
        arn: !GetAtt MyQueue.Arn

resources:
  Resources:
    MyQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: my-awesome-queue
```

Error:
![image](https://user-images.githubusercontent.com/79491580/229390525-dc78db67-8e05-4a50-a66f-cc2a80cc749d.png)

- Serverless version: **v2.4.0**
- Vscode Extension: **[YAML](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) by redhat**

**Comment by KillDozerX2** [comment]
Ahh! I knew this would happen, I will raise a PR shortly!

**Comment by KillDozerX2** [comment]
Actually, supporting CF Intrinsinc functions as string is an issue, I've added support for using GetAtt in the event though.
As of now, the only format that we can support is like this:-
```yml
functions:
  MyLambda:
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn
```
