### ISSUE TITLE
VPC Configuration: Incorrect type. Expected Aws_CF_Function

### ISSUE THREAD

**Issue by phmasek** [lalcebo/json-schema#166]
I get an error when trying to setup the configuration for VPC. 

```yaml
vpc:
  subnetIds:
    - ${self:custom.mongodb.subnet_id.${self:provider.stage}} // <-- Incorrect type. Expected "CFIntrinsicFunctionBase64 | CFIntrinsicFunctionCIDR | CFIntrinsicFunctionFindInMap | CFIntrinsicFunctionGetAttribute | CFIntrinsicFunctionGetAvailabilityZones | CFIntrinsicFunctionImportValue | CFIntrinsicFunctionJoin | object(CFIntrinsicFunctionRef) | CFIntrinsicFunctionSelect | CFIntrinsicFunctionSplit | CFIntrinsicFunctionSub | CFIntrinsicFunctionCovertToJsonString".
  securityGroupIds:
    - ${self:custom.mongodb.security_group_id.${self:provider.stage}} // <-- Incorrect type. Expected "CFIntrinsicFunctionBase64 | CFIntrinsicFunctionCIDR | CFIntrinsicFunctionFindInMap | CFIntrinsicFunctionGetAttribute | CFIntrinsicFunctionGetAvailabilityZones | CFIntrinsicFunctionImportValue | CFIntrinsicFunctionJoin | object(CFIntrinsicFunctionRef) | CFIntrinsicFunctionSelect | CFIntrinsicFunctionSplit | CFIntrinsicFunctionSub | CFIntrinsicFunctionCovertToJsonString".
```

[Official documentation](https://www.serverless.com/framework/docs/providers/aws/guide/functions#vpc-configuration) only mentions using array of strings. 
Not sure why these are set to expect Cloudformation functions? Is there some other way to configure this?

https://github.com/lalcebo/json-schema/blob/f5c51d594a90bb01b2b992787176504e53d992ea/serverless/reference.json#L1552-L1569

**Comment by adamghowiba** [comment]
This would be a huge help for us.

Facing this same issue, not sure how to work around it aside from just ignoring the error in the serverless.yml config. 

I'm also just using an array of strings, nothing fancy

```yml
vpc:
    securityGroupIds:
      - sg-08ddc5de489de1870
    subnetIds:
      - subnet-0bd3103df9c6b72e7
      - subnet-0fda3d05946d16509
      - subnet-01ea0d8230da6b492
```
