### ISSUE TITLE
Support for variable references

### ISSUE THREAD

**Issue by dnicolson** [lalcebo/json-schema#50]
Unless a property accepts the type string with no applicable validation constraints, variable references will cause validation errors. This can be seen in the [aws-ffmpeg-layer](https://github.com/serverless/examples/blob/156bfae/aws-ffmpeg-layer/serverless.yml) example:

![PixelSnap 2022-07-28 at 21 08 45@2x](https://user-images.githubusercontent.com/2276355/181618551-7825ab26-6adf-4b69-ae03-1a75c5d2fda0.png)

According to the [Serverless Variables](https://www.serverless.com/framework/docs/providers/aws/guide/variables) page, there are at least half a dozen variable formats. The CloudFormation reference is briefly mentioned in this [article](https://www.serverless.com/blog/publish-aws-lambda-layers-serverless-framework/).

I'm wondering what the best approach would be here, would it be feasible to use a pattern to match `{...}`/`${...}` values similar to the `Serverless.FilePath` sub schema?

**Comment by KillDozerX2** [comment]
@dnicolson we have the Expression in defintion, would that be a better solution?

**Comment by dnicolson** [comment]
@KillDozerX2 I am not sure what you mean, where is this Expression?

**Comment by Sparticuz** [comment]
I've also got this problem. I'm enabled event schedules based on stage.
```
custom:
  scheduleEnabled:
    prod: true
    dev: false

functions:
  move-to-tm:
    handler: dist/move-to-tm.default
    timeout: 30
    events:
      - schedule:
          rate: rate(7 days)
          enabled: ${self:custom.scheduleEnabled.${opt:stage, self:provider.stage}}
```
![image](https://user-images.githubusercontent.com/161913/197000259-86ca6126-03c6-4234-a697-a7f4bdec1d8b.png)
